#!/bin/bash
IP=`echo $SSH_CONNECTION | awk '{print $1}'`

#set default route
DEFAULT_ROUTE=`sudo /sbin/route | cut -d " " -f 1 | grep default`

sudo /sbin/route del default 2> /dev/null
sudo /sbin/route add default gw $IP

#        echo ""
#        echo "Share you internet connection from your pc copy following"
#        echo "command between --> and <-- into a local console from your pc:"
#        echo ""
#        echo "Ubuntu (sudo apt-get install gksudo)"
#        echo ""
#        echo "-->gksudo -u root -m \"Please insert your password to share your local internet connection\" \"su -c 'echo 1 > /proc/sys/net/ipv4/ip_forward && iptables -P FORWARD ACCEPT && iptables -A POSTROUTING -t nat -j MASQUERADE -s 10.0.0.0/24'\"<--"
#       echo ""
#        echo "Welcome to picosafe! You are now in your own private crypted world!"
#        echo ""
