#!/bin/bash
set -e
CONFIG="/etc/cgiemail.conf"

if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi

if [ "$1" = purge ]; then
	rm -f $CONFIG 2>/dev/null
fi

# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section

