#!/bin/sh
set -e

if [ -z "$2" ] || dpkg --compare-versions "$2" lt 6.1-6 ; then
  if [ ! -L /etc/udev/rules.d/z60_hdparm.rules ]; then
    ln -s ../hdparm.rules /etc/udev/rules.d/z60_hdparm.rules
  fi
fi

if [ -n "$2" ] && dpkg --compare-versions "$2" lt 8.9-2; then
  rm -fv /etc/rc0.d/K75hdparm /etc/rc6.d/K75hdparm
fi
# Automatically added by dh_installinit
if [ -x "/etc/init.d/hdparm" ]; then
	update-rc.d hdparm start 07 S . >/dev/null || exit $?
fi
# End automatically added section

