#!/bin/sh
if [ "x$D" != "x" ]; then
	install -d $D/opt/eldk-5.2.1/armv5te/sysroots/i686-eldk-linux/etc/rcS.d
	# this happens at S98 where our good 'ole packages script used to run
	echo "#!/bin/sh
opkg-cl configure
rm -f //opt/eldk-5.2.1/armv5te/sysroots/i686-eldk-linux/etc/rcS.d/S98run-postinsts
" > $D/opt/eldk-5.2.1/armv5te/sysroots/i686-eldk-linux/etc/rcS.d/S98run-postinsts
	chmod 0755 $D/opt/eldk-5.2.1/armv5te/sysroots/i686-eldk-linux/etc/rcS.d/S98run-postinsts
fi

update-alternatives --install /opt/eldk-5.2.1/armv5te/sysroots/i686-eldk-linux/usr/bin/opkg opkg /opt/eldk-5.2.1/armv5te/sysroots/i686-eldk-linux/usr/bin/opkg-cl 100
